parameters:
    journal.card.article.wikipedia.template: 'JournalBundle:Card:article/wikipedia.html.twig'
    journal.card.article.instagram.template: 'JournalBundle:Card:article/instagram.html.twig'
    journal.card.article.photo.template: 'JournalBundle:Card:article/photo.html.twig'
    journal.card.article.jenkins.template: 'JournalBundle:Card:article/jenkins.html.twig'

services:
    journal.card.article.wikipedia:
        parent: journal.card.wikipedia
        arguments:
            - %journal.card.article.wikipedia.template%
        tags:
            - { name: journal.card, type: journal.article.learn, position: 100 }

    # journal.card.article.jenkins:
    #     parent: journal.card.jenkins
    #     arguments:
    #         - %journal.card.article.jenkins.template%
    #     tags:
    #         - { name: journal.card, type: journal.article.work, position: 100 }

    journal.card.article.instagram:
        parent: journal.card.instagram
        arguments:
            - %journal.card.article.instagram.template%
        tags:
            - { name: journal.card, type: journal.article.picture, position: 100 }

    journal.card.article.flickr:
        parent: journal.card.flickr
        arguments:
            - %journal.card.article.photo.template%
        tags:
            - { name: journal.card, type: journal.article.picture, position: 100 }
