services:
    journal.registry.card:
        class: Application\Domain\CardRegistry

    journal.card.header.thin:
        class: JournalBundle\Card\HeaderCard
        arguments:
            - 'JournalBundle:Card:header/thin.html.twig'
            -
                title: Thin header
                description: Simple header card to introduce your journal
        tags:
            - { name: journal.card, type: journal.header, position: 15 }

    journal.card.article.quote:
        class: JournalBundle\Card\QuoteCard
        arguments:
            - 'JournalBundle:Card:article/quote.html.twig'
            -
                title: Simple quote
                description: A nice quote every day !
        tags:
            - { name: journal.card, type: journal.article.learn, position: 20 }

    journal.card.article.weather:
        class: JournalBundle\Card\WeatherCard
        arguments:
            - 'JournalBundle:Card:article/weather.html.twig'
            -
                title: Weather forecast
                description: Get the morning and evening forecast
        tags:
            - { name: journal.card, type: journal.article.weather, position: 30 }

    journal.card.article.sudoku:
        class: JournalBundle\Card\SudokuCard
        arguments:
            - 'JournalBundle:Card:article/sudoku.html.twig'
            -
                title: Sudoku game
                description: Fulfill a sudoku grid a day to keep the doctor away !
        tags:
            - { name: journal.card, type: journal.article.game, position: 40 }

    journal.card.article.instagram:
        class: JournalBundle\Card\InstagramCard
        arguments:
            - 'JournalBundle:Card:article/instagram.html.twig'
            -
                title: Instagram
                description: Get an instagram picture on each issue
        tags:
            - { name: journal.card, type: journal.article.picture, position: 50 }

    journal.card.article.flickr:
        class: JournalBundle\Card\FlickrCard
        arguments:
            - 'JournalBundle:Card:article/flickr.html.twig'
            -
                title: Flickr
                description: Get an flickr picture on each issue
        tags:
            - { name: journal.card, type: journal.article.picture, position: 50 }
