services:
    app.card.registry:
        class: Application\Domain\CardRegistry

    journal.card.base:
        class: JournalBundle\Card\BaseCard

    journal.card.header:
        class: JournalBundle\Card\HeaderCard

    journal.card.wikipedia:
        class: JournalBundle\Card\WikipediaCard

    journal.card.flickr:
        class: JournalBundle\Card\FlickrCard

    journal.card.instagram:
        class: JournalBundle\Card\InstagramCard

    journal.card.jenkins:
        class: JournalBundle\Card\JenkinsCard

    journal.card.sudoku:
        class: JournalBundle\Card\SudokuCard

    journal.card.quote:
        class: JournalBundle\Card\QuoteCard
